web:
  links:
    - php
  build: ./dockerfiles/nginx
  volumes_from:
    - php
  ports:
    - "8000:80"

php:
  links:
    - db
  expose:
    - 9000
  build: ./dockerfiles/php
  volumes:
    - ./media:/music

db:
  image: mariadb:10.0
  environment:
    - "MYSQL_ROOT_PASSWORD=root"
    - "MYSQL_USER=koel"
    - "MYSQL_PASSWORD=koel"
    - "MYSQL_DATABASE=koel"
  expose:
    - 3306
  volumes:
    - "/opt/koel/mysql:/var/lib/mysql/"
